apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ContainerPrivilegesRestriction
metadata:
  name: restrict-container-privileges
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]





